### ISSUE TITLE
Feature Request: Ability to define PGID/PUID for the docker container

### ISSUE THREAD

**Issue by jaybird2203** [SenexCrenshaw/StreamMaster#129]
**Is your feature request related to a problem? Please describe.**

- not directly, looking to minimize added steps from current workflow instead of needing to manually adjust owner/group definitions

**Describe the solution you'd like**

- simple PUID/PGID fields added to the template to define values as needed

**Describe alternatives you've considered**

- using midnight commander to move files into root owned folders instead of ability to drag drop direct from Windows

**Additional context**

- looking to avoid future permission based issues should someone miss reassigning after a move etc.

**Comment by SenexCrenshaw** [comment]
PLEASE TEST!!!
``senexcrenshaw/streammaster:SenexCrenshaw-issue129-0.2.18-SenexCrenshaw-issue129.1-0054``

NOTE: docker-compose changes
```
version: "3.4"

services:
  streanmaster:
    image: streammaster:latest
    ports:
      - 7095:7095
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/config
      - C:\Users\senex\source\repos\tv-logos:/config/tv-logos
```

https://github.com/SenexCrenshaw/StreamMaster/wiki/Installation#docker-compose

you probably will have to mess with permissions on the host side. LMK
